services:
  - type: web
    name: alshaer-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
    plan: free
    healthCheckPath: /api/health
    domains:
      - alshaer.onrender.com
      - www.alshaer.onrender.com
